using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Perf.SourceGenerator
{
    [Generator]
    public class PerfGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var methodDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m != null);

            context.RegisterSourceOutput(methodDeclarations, static (spc, source) => Execute(spc, source));
        }

        private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
        {
            return node is MethodDeclarationSyntax { AttributeLists.Count: > 0 };
        }

        private static IMethodSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var methodDeclaration = (MethodDeclarationSyntax)context.Node;
            
            foreach (var attributeListSyntax in methodDeclaration.AttributeLists)
            {
                foreach (var attributeSyntax in attributeListSyntax.Attributes)
                {
                    if (context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol is IMethodSymbol attributeSymbol)
                    {
                        var attributeContainingTypeSymbol = attributeSymbol.ContainingType;
                        var fullName = attributeContainingTypeSymbol.ToDisplayString();
                        
                        if (fullName == "Perf.Core.PerfAttribute")
                        {
                            return context.SemanticModel.GetDeclaredSymbol(methodDeclaration) as IMethodSymbol;
                        }
                    }
                }
            }
            return null;
        }

        private static void Execute(SourceProductionContext context, IMethodSymbol? methodSymbol)
        {
            if (methodSymbol == null) return;

            string namespaceName = methodSymbol.ContainingNamespace.ToDisplayString();
            string className = methodSymbol.ContainingType.Name;
            string originalMethodName = methodSymbol.Name;
            
            // Expected convention: method ends with _Impl
            string publicMethodName = originalMethodName.EndsWith("_Impl") 
                ? originalMethodName.Substring(0, originalMethodName.Length - 5) 
                : originalMethodName + "_Wrapper";

            string returnType = methodSymbol.ReturnType.ToDisplayString();
            bool isAsync = methodSymbol.IsAsync;
            bool returnsVoid = methodSymbol.ReturnsVoid;
            bool returnsTask = returnType.StartsWith("System.Threading.Tasks.Task");

            var parameters = methodSymbol.Parameters;
            string parametersSignature = string.Join(", ", parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"));
            string parametersCall = string.Join(", ", parameters.Select(p => p.Name));

            string opName = $"{namespaceName}.{className}.{publicMethodName}";
            ulong opId = CalculateFnv1a64(opName);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Perf.Core;");
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");
            
            // Constant OperationId cached at class level
            string opIdFieldName = $"__opId_{publicMethodName}";
            sb.AppendLine($"        private static readonly OperationId {opIdFieldName} = OperationRegistry.Register(\"{opName}\");");
            
            // Method signature
            string modifiers = "public"; // Assume public for generated API
            string asyncModifier = isAsync || returnsTask ? "async " : "";
            
            sb.AppendLine($"        {modifiers} {asyncModifier}{returnType} {publicMethodName}({parametersSignature})");
            sb.AppendLine("        {");
            sb.AppendLine($"            using var scope = (PerfScope)Perf.Measure({opIdFieldName});");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            
            string awaitKeyword = isAsync || returnsTask ? "await " : "";
            string returnKeyword = returnsVoid && !returnsTask ? "" : "return ";
            
            sb.AppendLine($"                {returnKeyword}{awaitKeyword}{originalMethodName}({parametersCall});");
            
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine("                scope.MarkFailed(ex);");
            sb.AppendLine("                throw;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource($"{className}_{publicMethodName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static ulong CalculateFnv1a64(string text)
        {
            ulong hash = 14695981039346656037UL;
            foreach (char c in text)
            {
                hash ^= c;
                hash *= 1099511628211UL;
            }
            return hash;
        }
    }
}
